GET https://goals-app-mern.herokuapp.com/api/goals


###
POST https://goals-app-mern.herokuapp.com/api/goals
Content-Type : application/json

{
    "title" : "Become IAS",
    "description" : "I want to become an IAS offier",
    "category": "personal",
    "completed" : false
}

###
PUT https://goals-app-mern.herokuapp.com/api/goals/608a05fad2468900150e5cbc
Content-Type : application/json

{
    "title" : "Read TAGR",
    "description" : "I want to read TAGR completely",
    "category": "personal",
    "completed" : false

}

###
DELETE https://goals-app-mern.herokuapp.com/api/goals/608a05460e04f6001581cb0b

###
GET http://localhost:5000